# Generated by Django 4.1.2 on 2022-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('pic_link', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1500)),
                ('pos', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['pid'], name='place_place_pid_93b918_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['rating'], name='place_place_rating_cc1674_idx'),
        ),
    ]
