# Generated by Django 4.1.2 on 2022-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='pos',
        ),
        migrations.AddField(
            model_name='place',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
