# Generated by Django 4.1.2 on 2022-10-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
