# Generated by Django 4.1.2 on 2022-10-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
