# Generated by Django 4.1.2 on 2022-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
