# Generated by Django 4.1.2 on 2022-10-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_alter_problem_pid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['pid'], name='problem_pro_pid_376afa_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['rating'], name='problem_pro_rating_43b56b_idx'),
        ),
    ]
