# Generated by Django 4.1.2 on 2022-10-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_problem_problem_pro_pid_376afa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
    ]
