# Generated by Django 4.1.2 on 2022-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problem_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answered',
            field=models.IntegerField(default=0),
        ),
    ]
