# Generated by Django 4.1.2 on 2022-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_problem_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
